//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildFeed.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VariantTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VariantTerms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildFeed.Local.VariantTerms", typeof(VariantTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âδδ βúïℓδ  !!!].
        /// </summary>
        public static string Common_AddBuild {
            get {
                return ResourceManager.GetString("Common_AddBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âδ₥ïñ  !!!].
        /// </summary>
        public static string Common_Admin {
            get {
                return ResourceManager.GetString("Common_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çôñƭřïβúƭè ôñ  !!!].
        /// </summary>
        public static string Common_ContributeOn {
            get {
                return ResourceManager.GetString("Common_ContributeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çřèδïƭƨ  !!!].
        /// </summary>
        public static string Common_Credits {
            get {
                return ResourceManager.GetString("Common_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÐèƲèℓôƥèδ β¥  !!!].
        /// </summary>
        public static string Common_DevelopedBy {
            get {
                return ResourceManager.GetString("Common_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éřřôř  !!!].
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ô₥èƭλïñϱ&apos;ƨ βřôƙè. Má¥βè ïƭ&apos;ƨ βèçáúƨè ¥ôú δïδ ƨô₥èƭλïñϱ ωèïřδ. Þřôβáβℓ¥ ïƭ&apos;ƨ βèçáúƨè Ì δïδ ƨô₥èƭλïñϱ ωèïřδ. Ìƒ ¥ôú ƙèèƥ ϱèƭƭïñϱ ƭλïƨ èřřôř, ƨúβ₥ïƭ á βúϱ řèƥôřƭ Ʋïá {0}. ℓôřè₥ ïƥƨú₥ δôℓôř ƨïƭ á₥ !!!].
        /// </summary>
        public static string Common_ErrorContent {
            get {
                return ResourceManager.GetString("Common_ErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ôϱ ïñ  !!!].
        /// </summary>
        public static string Common_LogIn {
            get {
                return ResourceManager.GetString("Common_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ôϱ ôúƭ  !!!].
        /// </summary>
        public static string Common_LogOut {
            get {
                return ResourceManager.GetString("Common_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £áñϱúáϱè ℓ !!!].
        /// </summary>
        public static string Common_NavigationLanguage {
            get {
                return ResourceManager.GetString("Common_NavigationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tλè₥è ℓ !!!].
        /// </summary>
        public static string Common_NavigationTheme {
            get {
                return ResourceManager.GetString("Common_NavigationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! R§§ ƒèèδƨ  !!!].
        /// </summary>
        public static string Common_RssFeeds {
            get {
                return ResourceManager.GetString("Common_RssFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ïƭè₥áƥ  !!!].
        /// </summary>
        public static string Common_Sitemap {
            get {
                return ResourceManager.GetString("Common_Sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ðářƙ  !!!].
        /// </summary>
        public static string Common_ThemeDark {
            get {
                return ResourceManager.GetString("Common_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ïϱλƭ ℓ !!!].
        /// </summary>
        public static string Common_ThemeLight {
            get {
                return ResourceManager.GetString("Common_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! | Þáϱè {0}  !!!].
        /// </summary>
        public static string Common_TitlePage {
            get {
                return ResourceManager.GetString("Common_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tôϱϱℓè ñáƲïϱáƭïôñ ℓ !!!].
        /// </summary>
        public static string Common_ToggleNavigation {
            get {
                return ResourceManager.GetString("Common_ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tωïƭƭèř  !!!].
        /// </summary>
        public static string Common_Twitter {
            get {
                return ResourceManager.GetString("Common_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âβôúƭ  !!!].
        /// </summary>
        public static string Front_About {
            get {
                return ResourceManager.GetString("Front_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âβôúƭ {0}  !!!].
        /// </summary>
        public static string Front_AboutSite {
            get {
                return ResourceManager.GetString("Front_AboutSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδƨ ƒřô₥ {0}  !!!].
        /// </summary>
        public static string Front_BuildsFrom {
            get {
                return ResourceManager.GetString("Front_BuildsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çô₥₥èñƭƨ  !!!].
        /// </summary>
        public static string Front_Comments {
            get {
                return ResourceManager.GetString("Front_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çúřřèñƭ Çáñář¥ ℓ !!!].
        /// </summary>
        public static string Front_CurrentCanary {
            get {
                return ResourceManager.GetString("Front_CurrentCanary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çúřřèñƭ Ìñƨïδèř ℓ !!!].
        /// </summary>
        public static string Front_CurrentInsider {
            get {
                return ResourceManager.GetString("Front_CurrentInsider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çúřřèñƭ Rèℓèáƨè ℓ !!!].
        /// </summary>
        public static string Front_CurrentRelease {
            get {
                return ResourceManager.GetString("Front_CurrentRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ðèℓèƭè  !!!].
        /// </summary>
        public static string Front_Delete {
            get {
                return ResourceManager.GetString("Front_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ðèƭáïℓƨ  !!!].
        /// </summary>
        public static string Front_Details {
            get {
                return ResourceManager.GetString("Front_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éδïƭ !!!].
        /// </summary>
        public static string Front_Edit {
            get {
                return ResourceManager.GetString("Front_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éδïƭ βúïℓδ  !!!].
        /// </summary>
        public static string Front_EditBuild {
            get {
                return ResourceManager.GetString("Front_EditBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éδïƭôř áçƭïôñƨ  !!!].
        /// </summary>
        public static string Front_EditorActions {
            get {
                return ResourceManager.GetString("Front_EditorActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §èè ƭλè ƒúℓℓ Wïñδôωƨ βúïℓδ ℓïƨƭïñϱ... ℓôřè₥ !!!].
        /// </summary>
        public static string Front_FullBuildListing {
            get {
                return ResourceManager.GetString("Front_FullBuildListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! {0}: Tλè Wïñδôωƨ βúïℓδ ƭřáçƙèř ℓôřè₥ ïƥ !!!].
        /// </summary>
        public static string Front_HomeH1 {
            get {
                return ResourceManager.GetString("Front_HomeH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! {0} βúïℓδ ℓïƨƭ ℓ !!!].
        /// </summary>
        public static string Front_HomepageH1 {
            get {
                return ResourceManager.GetString("Front_HomepageH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £áƭèƨƭ ßúïℓδƨ ℓ !!!].
        /// </summary>
        public static string Front_LatestBuilds {
            get {
                return ResourceManager.GetString("Front_LatestBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ïƨƭïñϱ  !!!].
        /// </summary>
        public static string Front_Listing {
            get {
                return ResourceManager.GetString("Front_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Fïñδ ₥ôřè βúïℓδƨ ƒřô₥ {0} ℓô !!!].
        /// </summary>
        public static string Front_MoreFromLab {
            get {
                return ResourceManager.GetString("Front_MoreFromLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Fïñδ ₥ôřè βúïℓδƨ ƨôúřçèδ ƒřô₥ {0} ℓô !!!].
        /// </summary>
        public static string Front_MoreFromSource {
            get {
                return ResourceManager.GetString("Front_MoreFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Fïñδ ₥ôřè βúïℓδƨ çô₥ƥïℓèδ ïñ {0} ℓô !!!].
        /// </summary>
        public static string Front_MoreFromYear {
            get {
                return ResourceManager.GetString("Front_MoreFromYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Nô ℓáβ ƨƭřïñϱ  !!!].
        /// </summary>
        public static string Front_NoLabString {
            get {
                return ResourceManager.GetString("Front_NoLabString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! {0} βúïℓδƨ  !!!].
        /// </summary>
        public static string Front_NumOfBuilds {
            get {
                return ResourceManager.GetString("Front_NumOfBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÞřïƲáƭè  !!!].
        /// </summary>
        public static string Front_Private {
            get {
                return ResourceManager.GetString("Front_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Þúβℓïç  !!!].
        /// </summary>
        public static string Front_Public {
            get {
                return ResourceManager.GetString("Front_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Qúïçƙ-ƥáƨƭè  !!!].
        /// </summary>
        public static string Front_QuickPaste {
            get {
                return ResourceManager.GetString("Front_QuickPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèƭúřñ ƭô βúïℓδ ℓïƨƭïñϱ ℓ !!!].
        /// </summary>
        public static string Front_ReturnToListing {
            get {
                return ResourceManager.GetString("Front_ReturnToListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèƭúřñ ƭô βúïℓδ ôƲèřƲïèω ℓ !!!].
        /// </summary>
        public static string Front_ReturnToOverview {
            get {
                return ResourceManager.GetString("Front_ReturnToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §λářè  !!!].
        /// </summary>
        public static string Front_Share {
            get {
                return ResourceManager.GetString("Front_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tôδá¥  !!!].
        /// </summary>
        public static string Front_Today {
            get {
                return ResourceManager.GetString("Front_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÐïƨçôƲèř áβôúƭ Wïñδôωƨ ßúïℓδ {0}, ƒřô₥ {1} áñδ çô₥ƥïℓèδ ôñ {2}. ℓôřè₥ !!!].
        /// </summary>
        public static string Meta_BuildDate {
            get {
                return ResourceManager.GetString("Meta_BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÐïƨçôƲèř áβôúƭ Wïñδôωƨ ßúïℓδ {0}, ƒřô₥ {1}. ßúïℓδFèèδ ƭřáçƙƨ Wïñδôωƨ βúïℓδƨ ƭλřôúϱλôúƭ ƭλè δèƲèℓôƥ₥èñƭ ƥřôçèƨƨ. ℓôřè₥ ïƥƨú !!!].
        /// </summary>
        public static string Meta_BuildNoDate {
            get {
                return ResourceManager.GetString("Meta_BuildNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çλèçƙ ôúƭ áℓℓ ƭλè ƙñôωñ βúïℓδƨ ƭô çô₥è ôúƭ ôƒ ƭλè Wïñδôωƨ δèƲèℓôƥ₥èñƭ ℓáβ {0} ƭλřôúϱλ ßúïℓδFèèδ, á çôℓℓáβôřáƭïƲè Wïñδôωƨ βúïℓδ ℓïƨƭ ℓôřè₥ ïƥƨú₥  !!!].
        /// </summary>
        public static string Meta_LabGeneric {
            get {
                return ResourceManager.GetString("Meta_LabGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Vïèω á ℓïƨƭ ôƒ áℓℓ Wïñδôωƨ βúïℓδƨ çô₥ƥïℓèδ ïñ {0}, áñδ ωáƭçλ λôω Wïñδôωƨ δèƲèℓôƥèδ ƨƭèáδïℓ¥ ôƲèř ƭï₥è, ƭλřôúϱλ ƭλè çôℓℓáβôřáƭïƲè βúïℓδ ℓïƨƭ, ßúïℓδFèèδ ℓôřè₥ ïƥƨú₥ δô !!!].
        /// </summary>
        public static string Meta_YearGeneric {
            get {
                return ResourceManager.GetString("Meta_YearGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tï₥è çřèáƭèδ  !!!].
        /// </summary>
        public static string Model_Added {
            get {
                return ResourceManager.GetString("Model_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ ñú₥βèř  !!!].
        /// </summary>
        public static string Model_BuildNumber {
            get {
                return ResourceManager.GetString("Model_BuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ ƭï₥è  !!!].
        /// </summary>
        public static string Model_BuildTime {
            get {
                return ResourceManager.GetString("Model_BuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éжƭèřñáℓ £ïñƙ ℓ !!!].
        /// </summary>
        public static string Model_ExternalLink {
            get {
                return ResourceManager.GetString("Model_ExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £áβ ƨƭřïñϱ  !!!].
        /// </summary>
        public static string Model_LabString {
            get {
                return ResourceManager.GetString("Model_LabString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £èáƙ ôř řèℓèáƨè δáƭè ℓ !!!].
        /// </summary>
        public static string Model_LeakDate {
            get {
                return ResourceManager.GetString("Model_LeakDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! MáJôř Ʋèřƨïôñ  !!!].
        /// </summary>
        public static string Model_MajorVersion {
            get {
                return ResourceManager.GetString("Model_MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Mïñôř Ʋèřƨïôñ  !!!].
        /// </summary>
        public static string Model_MinorVersion {
            get {
                return ResourceManager.GetString("Model_MinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tï₥è ₥ôδïƒïèδ  !!!].
        /// </summary>
        public static string Model_Modified {
            get {
                return ResourceManager.GetString("Model_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ řèƲïƨïôñ  !!!].
        /// </summary>
        public static string Model_Revision {
            get {
                return ResourceManager.GetString("Model_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âƥƥ ƥáçƙáϱè  !!!].
        /// </summary>
        public static string Model_Source_AppPackage {
            get {
                return ResourceManager.GetString("Model_Source_AppPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ ƭôôℓƨ  !!!].
        /// </summary>
        public static string Model_Source_BuildTools {
            get {
                return ResourceManager.GetString("Model_Source_BuildTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ðôçú₥èñƭáƭïôñ  !!!].
        /// </summary>
        public static string Model_Source_Documentation {
            get {
                return ResourceManager.GetString("Model_Source_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Þúβℓïç ℓèáƙ  !!!].
        /// </summary>
        public static string Model_Source_InternalLeak {
            get {
                return ResourceManager.GetString("Model_Source_InternalLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ôϱϱïñϱ  !!!].
        /// </summary>
        public static string Model_Source_Logging {
            get {
                return ResourceManager.GetString("Model_Source_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÞřïƲáƭè ℓèáƙ  !!!].
        /// </summary>
        public static string Model_Source_PrivateLeak {
            get {
                return ResourceManager.GetString("Model_Source_PrivateLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Þúβℓïç řèℓèáƨè  !!!].
        /// </summary>
        public static string Model_Source_PublicRelease {
            get {
                return ResourceManager.GetString("Model_Source_PublicRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ûƥδáƭè (GÐR)  !!!].
        /// </summary>
        public static string Model_Source_UpdateGDR {
            get {
                return ResourceManager.GetString("Model_Source_UpdateGDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ûƥδáƭè (£ÐR)  !!!].
        /// </summary>
        public static string Model_Source_UpdateLDR {
            get {
                return ResourceManager.GetString("Model_Source_UpdateLDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ôúřçè δèƭáïℓƨ  !!!].
        /// </summary>
        public static string Model_SourceDetails {
            get {
                return ResourceManager.GetString("Model_SourceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ôúřçè ƭ¥ƥè  !!!].
        /// </summary>
        public static string Model_SourceType {
            get {
                return ResourceManager.GetString("Model_SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ ℓ !!!].
        /// </summary>
        public static string Search_Build {
            get {
                return ResourceManager.GetString("Search_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §èářçλ ßúïℓδFèèδ... ℓ !!!].
        /// </summary>
        public static string Search_BuildFeed {
            get {
                return ResourceManager.GetString("Search_BuildFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Nô řèƨúℓƭƨ ƒôúñδ ℓ !!!].
        /// </summary>
        public static string Search_Empty {
            get {
                return ResourceManager.GetString("Search_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £áβ  !!!].
        /// </summary>
        public static string Search_Lab {
            get {
                return ResourceManager.GetString("Search_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §èářçλ 9úèř¥  !!!].
        /// </summary>
        public static string Search_Query {
            get {
                return ResourceManager.GetString("Search_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ôúrçè l !!!].
        /// </summary>
        public static string Search_Source {
            get {
                return ResourceManager.GetString("Search_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §èářçλ  !!!].
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ƭ¥ƥè ƭô ƨèářçλ... ℓ !!!].
        /// </summary>
        public static string Search_TypePlaceholder {
            get {
                return ResourceManager.GetString("Search_TypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Vèřƨïôñ ℓ !!!].
        /// </summary>
        public static string Search_Version {
            get {
                return ResourceManager.GetString("Search_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ýèář  !!!].
        /// </summary>
        public static string Search_Year {
            get {
                return ResourceManager.GetString("Search_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÉƲèř¥ áççôúñƭ ïƨ Ʋáℓïδáƭèδ β¥ áñ Âδ₥ïñïƨƭřáƭôř, ƨô βè ƥáƭïèñƭ áñδ çλèçƙ áϱáïñ ℓáƭèř. ℓôřè₥ ï !!!].
        /// </summary>
        public static string Support_AccountValidation {
            get {
                return ResourceManager.GetString("Support_AccountValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âδδïƭïôñƨ ƭô ßúïℓδFèèδ ℓ !!!].
        /// </summary>
        public static string Support_AdditionsToBuildFeed {
            get {
                return ResourceManager.GetString("Support_AdditionsToBuildFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδƨ Çô₥ƥïℓèδ ℓ !!!].
        /// </summary>
        public static string Support_BuildsCompiled {
            get {
                return ResourceManager.GetString("Support_BuildsCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çλáñϱè ¥ôúř ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string Support_ChangePassword {
            get {
                return ResourceManager.GetString("Support_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çôñƒïř₥ ñèω ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string Support_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Support_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çôñƒïř₥ ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string Support_ConfirmPassword {
            get {
                return ResourceManager.GetString("Support_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! É₥áïℓ áδδřèƨƨ  !!!].
        /// </summary>
        public static string Support_EmailAddress {
            get {
                return ResourceManager.GetString("Support_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éñƭèř çúřřèñƭ ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string Support_EnterCurrentPassword {
            get {
                return ResourceManager.GetString("Support_EnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éñƭèř ñèω ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string Support_EnterNewPassword {
            get {
                return ResourceManager.GetString("Support_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éñƭèř ƥáƨƨωôřδ  !!!].
        /// </summary>
        public static string Support_EnterPassword {
            get {
                return ResourceManager.GetString("Support_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Hïϱλèƨƭ Ʋèřƨïôñ ℓ !!!].
        /// </summary>
        public static string Support_HighestVersion {
            get {
                return ResourceManager.GetString("Support_HighestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £áβƨ !!!].
        /// </summary>
        public static string Support_Labs {
            get {
                return ResourceManager.GetString("Support_Labs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ôϱ ïñ  !!!].
        /// </summary>
        public static string Support_Login {
            get {
                return ResourceManager.GetString("Support_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Þáƨƨωôřδ  !!!].
        /// </summary>
        public static string Support_Password {
            get {
                return ResourceManager.GetString("Support_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèçèñƭℓ¥ áδδèδ  !!!].
        /// </summary>
        public static string Support_RecentlyAdded {
            get {
                return ResourceManager.GetString("Support_RecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèçèñƭℓ¥ çô₥ƥïℓèδ ℓ !!!].
        /// </summary>
        public static string Support_RecentlyCompiled {
            get {
                return ResourceManager.GetString("Support_RecentlyCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèçèñƭℓ¥ ℓèáƙèδ ℓ !!!].
        /// </summary>
        public static string Support_RecentlyLeaked {
            get {
                return ResourceManager.GetString("Support_RecentlyLeaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèϱïƨƭèř  !!!].
        /// </summary>
        public static string Support_Register {
            get {
                return ResourceManager.GetString("Support_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rè₥è₥βèř ₥è  !!!].
        /// </summary>
        public static string Support_RememberMe {
            get {
                return ResourceManager.GetString("Support_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tλáñƙ ¥ôú ƒôř řèϱïƨƭèřïñϱ ℓô !!!].
        /// </summary>
        public static string Support_ThanksRegister {
            get {
                return ResourceManager.GetString("Support_ThanksRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ûƨèřñá₥è  !!!].
        /// </summary>
        public static string Support_UserName {
            get {
                return ResourceManager.GetString("Support_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Wèèƙ !!!].
        /// </summary>
        public static string Support_Week {
            get {
                return ResourceManager.GetString("Support_Week", resourceCulture);
            }
        }
    }
}
