//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildFeed.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VariantTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VariantTerms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildFeed.Local.VariantTerms", typeof(VariantTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildFeed is ran and maintained by a group of enthusiasts. Microsoft are not involved in the site in any way. We&apos;ve certainly had no formal complaint from Microsoft about the site, even though we are certain they are aware of the site. That said, Microsoft obviously wish to keep private information private, and so we&apos;ve had sources shut down by them in the past, and I&apos;m sure they will in the future..
        /// </summary>
        public static string About_A1 {
            get {
                return ResourceManager.GetString("About_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice try, Dona, but I&apos;m not falling for this one. What I can say is this. BuildFeed makes as certain as is possible that all builds posted on the site are correct and legitimate. We have a number of different sources, to make verification more reliable and to give us some redundancy should Microsoft shut down one of our sources..
        /// </summary>
        public static string About_A2 {
            get {
                return ResourceManager.GetString("About_A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a number of ways. You can discuss the builds in the disqus comments system on each build page. You can also contribute to the site&apos;s development by reporting bugs or making pull requests on our GitHub. Lastly, you can help translate BuildFeed into your native language through our Translation portal..
        /// </summary>
        public static string About_A3 {
            get {
                return ResourceManager.GetString("About_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who runs BuildFeed? Is this an official Microsoft site?.
        /// </summary>
        public static string About_Q1 {
            get {
                return ResourceManager.GetString("About_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does BuildFeed get its data exactly?.
        /// </summary>
        public static string About_Q2 {
            get {
                return ResourceManager.GetString("About_Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I get involved?.
        /// </summary>
        public static string About_Q3 {
            get {
                return ResourceManager.GetString("About_Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add build.
        /// </summary>
        public static string Common_AddBuild {
            get {
                return ResourceManager.GetString("Common_AddBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bulk.
        /// </summary>
        public static string Common_AddBulk {
            get {
                return ResourceManager.GetString("Common_AddBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Common_Admin {
            get {
                return ResourceManager.GetString("Common_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute on {0}.
        /// </summary>
        public static string Common_ContributeOn {
            get {
                return ResourceManager.GetString("Common_ContributeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Common_Credits {
            get {
                return ResourceManager.GetString("Common_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by {0}.
        /// </summary>
        public static string Common_DevelopedBy {
            get {
                return ResourceManager.GetString("Common_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something&apos;s broke. Maybe it&apos;s because you did something weird. Probably because I did something weird. If you keep getting this error, submit a bug report via {0}..
        /// </summary>
        public static string Common_ErrorContent {
            get {
                return ResourceManager.GetString("Common_ErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Common_LogIn {
            get {
                return ResourceManager.GetString("Common_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Common_LogOut {
            get {
                return ResourceManager.GetString("Common_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Common_NavigationLanguage {
            get {
                return ResourceManager.GetString("Common_NavigationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Common_NavigationTheme {
            get {
                return ResourceManager.GetString("Common_NavigationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS feeds.
        /// </summary>
        public static string Common_RssFeeds {
            get {
                return ResourceManager.GetString("Common_RssFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        public static string Common_Sitemap {
            get {
                return ResourceManager.GetString("Common_Sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Common_ThemeDark {
            get {
                return ResourceManager.GetString("Common_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Common_ThemeLight {
            get {
                return ResourceManager.GetString("Common_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Page {0}.
        /// </summary>
        public static string Common_TitlePage {
            get {
                return ResourceManager.GetString("Common_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string Common_ToggleNavigation {
            get {
                return ResourceManager.GetString("Common_ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Common_Twitter {
            get {
                return ResourceManager.GetString("Common_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Front_About {
            get {
                return ResourceManager.GetString("Front_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string Front_AboutSite {
            get {
                return ResourceManager.GetString("Front_AboutSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds from {0}.
        /// </summary>
        public static string Front_BuildsFrom {
            get {
                return ResourceManager.GetString("Front_BuildsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Front_Comments {
            get {
                return ResourceManager.GetString("Front_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Canary.
        /// </summary>
        public static string Front_CurrentCanary {
            get {
                return ResourceManager.GetString("Front_CurrentCanary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Insider.
        /// </summary>
        public static string Front_CurrentInsider {
            get {
                return ResourceManager.GetString("Front_CurrentInsider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Release.
        /// </summary>
        public static string Front_CurrentRelease {
            get {
                return ResourceManager.GetString("Front_CurrentRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Xbox.
        /// </summary>
        public static string Front_CurrentXbox {
            get {
                return ResourceManager.GetString("Front_CurrentXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Front_Delete {
            get {
                return ResourceManager.GetString("Front_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Front_Details {
            get {
                return ResourceManager.GetString("Front_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Front_Edit {
            get {
                return ResourceManager.GetString("Front_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit build.
        /// </summary>
        public static string Front_EditBuild {
            get {
                return ResourceManager.GetString("Front_EditBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor actions.
        /// </summary>
        public static string Front_EditorActions {
            get {
                return ResourceManager.GetString("Front_EditorActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the full Windows build listing....
        /// </summary>
        public static string Front_FullBuildListing {
            get {
                return ResourceManager.GetString("Front_FullBuildListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The Windows build tracker.
        /// </summary>
        public static string Front_HomeH1 {
            get {
                return ResourceManager.GetString("Front_HomeH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} build list.
        /// </summary>
        public static string Front_HomepageH1 {
            get {
                return ResourceManager.GetString("Front_HomepageH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest builds.
        /// </summary>
        public static string Front_LatestBuilds {
            get {
                return ResourceManager.GetString("Front_LatestBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string Front_Listing {
            get {
                return ResourceManager.GetString("Front_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more builds from {0}.
        /// </summary>
        public static string Front_MoreFromLab {
            get {
                return ResourceManager.GetString("Front_MoreFromLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more builds sourced from {0}.
        /// </summary>
        public static string Front_MoreFromSource {
            get {
                return ResourceManager.GetString("Front_MoreFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more builds compiled in {0}.
        /// </summary>
        public static string Front_MoreFromYear {
            get {
                return ResourceManager.GetString("Front_MoreFromYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lab string.
        /// </summary>
        public static string Front_NoLabString {
            get {
                return ResourceManager.GetString("Front_NoLabString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} builds.
        /// </summary>
        public static string Front_NumOfBuilds {
            get {
                return ResourceManager.GetString("Front_NumOfBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Front_Private {
            get {
                return ResourceManager.GetString("Front_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Front_Public {
            get {
                return ResourceManager.GetString("Front_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick-paste.
        /// </summary>
        public static string Front_QuickPaste {
            get {
                return ResourceManager.GetString("Front_QuickPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to build listing.
        /// </summary>
        public static string Front_ReturnToListing {
            get {
                return ResourceManager.GetString("Front_ReturnToListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to build overview.
        /// </summary>
        public static string Front_ReturnToOverview {
            get {
                return ResourceManager.GetString("Front_ReturnToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Front_Share {
            get {
                return ResourceManager.GetString("Front_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Front_Today {
            get {
                return ResourceManager.GetString("Front_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover about Windows Build {0}, from {1} and compiled on {2}..
        /// </summary>
        public static string Meta_BuildDate {
            get {
                return ResourceManager.GetString("Meta_BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover about Windows Build {0}, from {1}. BuildFeed tracks Windows builds throughout the development process..
        /// </summary>
        public static string Meta_BuildNoDate {
            get {
                return ResourceManager.GetString("Meta_BuildNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out all the known builds to come out of the Windows development lab {0} through BuildFeed, a collaborative Windows build list..
        /// </summary>
        public static string Meta_LabGeneric {
            get {
                return ResourceManager.GetString("Meta_LabGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a list of all Windows builds compiled in {0}, and watch how Windows developed steadily over time, through the collaborative build list, BuildFeed..
        /// </summary>
        public static string Meta_YearGeneric {
            get {
                return ResourceManager.GetString("Meta_YearGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time created.
        /// </summary>
        public static string Model_Added {
            get {
                return ResourceManager.GetString("Model_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build number.
        /// </summary>
        public static string Model_BuildNumber {
            get {
                return ResourceManager.GetString("Model_BuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build time.
        /// </summary>
        public static string Model_BuildTime {
            get {
                return ResourceManager.GetString("Model_BuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External link.
        /// </summary>
        public static string Model_ExternalLink {
            get {
                return ResourceManager.GetString("Model_ExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab string.
        /// </summary>
        public static string Model_LabString {
            get {
                return ResourceManager.GetString("Model_LabString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak or release date.
        /// </summary>
        public static string Model_LeakDate {
            get {
                return ResourceManager.GetString("Model_LeakDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major version.
        /// </summary>
        public static string Model_MajorVersion {
            get {
                return ResourceManager.GetString("Model_MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor version.
        /// </summary>
        public static string Model_MinorVersion {
            get {
                return ResourceManager.GetString("Model_MinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time modified.
        /// </summary>
        public static string Model_Modified {
            get {
                return ResourceManager.GetString("Model_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build revision.
        /// </summary>
        public static string Model_Revision {
            get {
                return ResourceManager.GetString("Model_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App package.
        /// </summary>
        public static string Model_Source_AppPackage {
            get {
                return ResourceManager.GetString("Model_Source_AppPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build tools.
        /// </summary>
        public static string Model_Source_BuildTools {
            get {
                return ResourceManager.GetString("Model_Source_BuildTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Model_Source_Documentation {
            get {
                return ResourceManager.GetString("Model_Source_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public leak.
        /// </summary>
        public static string Model_Source_InternalLeak {
            get {
                return ResourceManager.GetString("Model_Source_InternalLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Model_Source_Logging {
            get {
                return ResourceManager.GetString("Model_Source_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private leak.
        /// </summary>
        public static string Model_Source_PrivateLeak {
            get {
                return ResourceManager.GetString("Model_Source_PrivateLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public release.
        /// </summary>
        public static string Model_Source_PublicRelease {
            get {
                return ResourceManager.GetString("Model_Source_PublicRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (GDR).
        /// </summary>
        public static string Model_Source_UpdateGDR {
            get {
                return ResourceManager.GetString("Model_Source_UpdateGDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (LDR).
        /// </summary>
        public static string Model_Source_UpdateLDR {
            get {
                return ResourceManager.GetString("Model_Source_UpdateLDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source details.
        /// </summary>
        public static string Model_SourceDetails {
            get {
                return ResourceManager.GetString("Model_SourceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source type.
        /// </summary>
        public static string Model_SourceType {
            get {
                return ResourceManager.GetString("Model_SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Search_Build {
            get {
                return ResourceManager.GetString("Search_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search BuildFeed.
        /// </summary>
        public static string Search_BuildFeed {
            get {
                return ResourceManager.GetString("Search_BuildFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string Search_Empty {
            get {
                return ResourceManager.GetString("Search_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        public static string Search_Lab {
            get {
                return ResourceManager.GetString("Search_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search query.
        /// </summary>
        public static string Search_Query {
            get {
                return ResourceManager.GetString("Search_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Search_Source {
            get {
                return ResourceManager.GetString("Search_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search....
        /// </summary>
        public static string Search_TypePlaceholder {
            get {
                return ResourceManager.GetString("Search_TypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Search_Version {
            get {
                return ResourceManager.GetString("Search_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Search_Year {
            get {
                return ResourceManager.GetString("Search_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every account is validated by an administrator, so be patient and check again later.
        /// </summary>
        public static string Support_AccountValidation {
            get {
                return ResourceManager.GetString("Support_AccountValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additions to BuildFeed.
        /// </summary>
        public static string Support_AdditionsToBuildFeed {
            get {
                return ResourceManager.GetString("Support_AdditionsToBuildFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds compiled.
        /// </summary>
        public static string Support_BuildsCompiled {
            get {
                return ResourceManager.GetString("Support_BuildsCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string Support_ChangePassword {
            get {
                return ResourceManager.GetString("Support_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Support_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Support_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Support_ConfirmPassword {
            get {
                return ResourceManager.GetString("Support_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Support_EmailAddress {
            get {
                return ResourceManager.GetString("Support_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter current password.
        /// </summary>
        public static string Support_EnterCurrentPassword {
            get {
                return ResourceManager.GetString("Support_EnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string Support_EnterNewPassword {
            get {
                return ResourceManager.GetString("Support_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string Support_EnterPassword {
            get {
                return ResourceManager.GetString("Support_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest version.
        /// </summary>
        public static string Support_HighestVersion {
            get {
                return ResourceManager.GetString("Support_HighestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labs.
        /// </summary>
        public static string Support_Labs {
            get {
                return ResourceManager.GetString("Support_Labs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Support_Login {
            get {
                return ResourceManager.GetString("Support_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Support_Password {
            get {
                return ResourceManager.GetString("Support_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently added.
        /// </summary>
        public static string Support_RecentlyAdded {
            get {
                return ResourceManager.GetString("Support_RecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently compiled.
        /// </summary>
        public static string Support_RecentlyCompiled {
            get {
                return ResourceManager.GetString("Support_RecentlyCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently leaked.
        /// </summary>
        public static string Support_RecentlyLeaked {
            get {
                return ResourceManager.GetString("Support_RecentlyLeaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Support_Register {
            get {
                return ResourceManager.GetString("Support_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Support_RememberMe {
            get {
                return ResourceManager.GetString("Support_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering.
        /// </summary>
        public static string Support_ThanksRegister {
            get {
                return ResourceManager.GetString("Support_ThanksRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Support_UserName {
            get {
                return ResourceManager.GetString("Support_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Support_Week {
            get {
                return ResourceManager.GetString("Support_Week", resourceCulture);
            }
        }
    }
}
