//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildFeed.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildFeed.Local.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âδδ βúïℓδ  !!!].
        /// </summary>
        public static string AddBuild {
            get {
                return ResourceManager.GetString("AddBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âδ₥ïñ  !!!].
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çôñƭřïβúƭè ôñ  !!!].
        /// </summary>
        public static string ContributeOn {
            get {
                return ResourceManager.GetString("ContributeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çřèδïƭƨ  !!!].
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÐèƲèℓôƥèδ β¥  !!!].
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éřřôř  !!!].
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ôϱ ïñ  !!!].
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ôϱ ôúƭ  !!!].
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! | Þáϱè {0}  !!!].
        /// </summary>
        public static string PageTitleSegment {
            get {
                return ResourceManager.GetString("PageTitleSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Wïñδôωƨ NT  !!!].
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! R§§ ƒèèδƨ  !!!].
        /// </summary>
        public static string RssFeeds {
            get {
                return ResourceManager.GetString("RssFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §èářçλ  !!!].
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ ℓ !!!].
        /// </summary>
        public static string SearchBuild {
            get {
                return ResourceManager.GetString("SearchBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §èářçλ ßúïℓδFèèδ... ℓ !!!].
        /// </summary>
        public static string SearchBuildFeed {
            get {
                return ResourceManager.GetString("SearchBuildFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Nô řèƨúℓƭƨ ƒôúñδ ℓ !!!].
        /// </summary>
        public static string SearchEmpty {
            get {
                return ResourceManager.GetString("SearchEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £áβ  !!!].
        /// </summary>
        public static string SearchLab {
            get {
                return ResourceManager.GetString("SearchLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §èářçλ 9úèř¥  !!!].
        /// </summary>
        public static string SearchQuery {
            get {
                return ResourceManager.GetString("SearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ôúrçè l !!!].
        /// </summary>
        public static string SearchSource {
            get {
                return ResourceManager.GetString("SearchSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Vèřƨïôñ ℓ !!!].
        /// </summary>
        public static string SearchVersion {
            get {
                return ResourceManager.GetString("SearchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ýèář  !!!].
        /// </summary>
        public static string SearchYear {
            get {
                return ResourceManager.GetString("SearchYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ïƭè₥áƥ  !!!].
        /// </summary>
        public static string Sitemap {
            get {
                return ResourceManager.GetString("Sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδFèèδ  !!!].
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ƭáƭïƨƭïçƨ  !!!].
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tôϱϱℓè ñáƲïϱáƭïôñ ℓ !!!].
        /// </summary>
        public static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tωïƭƭèř  !!!].
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ƭ¥ƥè ƭô ƨèářçλ... ℓ !!!].
        /// </summary>
        public static string TypeToSearch {
            get {
                return ResourceManager.GetString("TypeToSearch", resourceCulture);
            }
        }
    }
}
