//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildFeed.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Front {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Front() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildFeed.Local.Front", typeof(Front).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a build.
        /// </summary>
        public static string AddABuild {
            get {
                return ResourceManager.GetString("AddABuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover about Windows Build {0}, from {1} and compiled on {2}..
        /// </summary>
        public static string BuildMetaDate {
            get {
                return ResourceManager.GetString("BuildMetaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover about Windows Build {0}, from {1}. BuildFeed tracks Windows builds throughout the development process..
        /// </summary>
        public static string BuildMetaNoDate {
            get {
                return ResourceManager.GetString("BuildMetaNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds from.
        /// </summary>
        public static string BuildsFrom {
            get {
                return ResourceManager.GetString("BuildsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit build.
        /// </summary>
        public static string EditBuild {
            get {
                return ResourceManager.GetString("EditBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor actions.
        /// </summary>
        public static string EditorActions {
            get {
                return ResourceManager.GetString("EditorActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows NT build list.
        /// </summary>
        public static string HomepageH1 {
            get {
                return ResourceManager.GetString("HomepageH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out all the known builds to come out of the Windows development lab {0} through BuildFeed, a collaborative Windows build list.
        /// </summary>
        public static string LabMetaGeneric {
            get {
                return ResourceManager.GetString("LabMetaGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string Listing {
            get {
                return ResourceManager.GetString("Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more builds from {0}.
        /// </summary>
        public static string MoreFromLab {
            get {
                return ResourceManager.GetString("MoreFromLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more builds sourced from {0}.
        /// </summary>
        public static string MoreFromSource {
            get {
                return ResourceManager.GetString("MoreFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more builds compiled in {0}.
        /// </summary>
        public static string MoreFromYear {
            get {
                return ResourceManager.GetString("MoreFromYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lab string.
        /// </summary>
        public static string NoLab {
            get {
                return ResourceManager.GetString("NoLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick-paste.
        /// </summary>
        public static string QuickPaste {
            get {
                return ResourceManager.GetString("QuickPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to build listing.
        /// </summary>
        public static string ReturnToListing {
            get {
                return ResourceManager.GetString("ReturnToListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to build overview.
        /// </summary>
        public static string ReturnToOverview {
            get {
                return ResourceManager.GetString("ReturnToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to builds.
        /// </summary>
        public static string xBuilds {
            get {
                return ResourceManager.GetString("xBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a list of all Windows builds compiled in {0}, and watch how Windows developed steadily over time, through the collaborative build list, BuildFeed.
        /// </summary>
        public static string YearMetaGeneric {
            get {
                return ResourceManager.GetString("YearMetaGeneric", resourceCulture);
            }
        }
    }
}
