//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildFeed.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Front {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Front() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildFeed.Local.Front", typeof(Front).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âβôúƭ  !!!].
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âδδ á βúïℓδ  !!!].
        /// </summary>
        public static string AddABuild {
            get {
                return ResourceManager.GetString("AddABuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÐïƨçôƲèř áβôúƭ Wïñδôωƨ ßúïℓδ {0}, ƒřô₥ {1} áñδ çô₥ƥïℓèδ ôñ {2}. ℓôřè₥ !!!].
        /// </summary>
        public static string BuildMetaDate {
            get {
                return ResourceManager.GetString("BuildMetaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÐïƨçôƲèř áβôúƭ Wïñδôωƨ ßúïℓδ {0}, ƒřô₥ {1}. ßúïℓδFèèδ ƭřáçƙƨ Wïñδôωƨ βúïℓδƨ ƭλřôúϱλôúƭ ƭλè δèƲèℓôƥ₥èñƭ ƥřôçèƨƨ. ℓôřè₥ ïƥƨú !!!].
        /// </summary>
        public static string BuildMetaNoDate {
            get {
                return ResourceManager.GetString("BuildMetaNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδƨ ƒřô₥ {0}  !!!].
        /// </summary>
        public static string BuildsFrom {
            get {
                return ResourceManager.GetString("BuildsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çô₥₥èñƭƨ  !!!].
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ðèℓèƭè  !!!].
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éδïƭ !!!].
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éδïƭ βúïℓδ  !!!].
        /// </summary>
        public static string EditBuild {
            get {
                return ResourceManager.GetString("EditBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éδïƭôř áçƭïôñƨ  !!!].
        /// </summary>
        public static string EditorActions {
            get {
                return ResourceManager.GetString("EditorActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Wïñδôωƨ NT βúïℓδ ℓïƨƭ ℓ !!!].
        /// </summary>
        public static string HomepageH1 {
            get {
                return ResourceManager.GetString("HomepageH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çλèçƙ ôúƭ áℓℓ ƭλè ƙñôωñ βúïℓδƨ ƭô çô₥è ôúƭ ôƒ ƭλè Wïñδôωƨ δèƲèℓôƥ₥èñƭ ℓáβ {0} ƭλřôúϱλ ßúïℓδFèèδ, á çôℓℓáβôřáƭïƲè Wïñδôωƨ βúïℓδ ℓïƨƭ ℓôřè₥ ïƥƨú₥  !!!].
        /// </summary>
        public static string LabMetaGeneric {
            get {
                return ResourceManager.GetString("LabMetaGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ïƨƭïñϱ  !!!].
        /// </summary>
        public static string Listing {
            get {
                return ResourceManager.GetString("Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Fïñδ ₥ôřè βúïℓδƨ ƒřô₥ {0} ℓô !!!].
        /// </summary>
        public static string MoreFromLab {
            get {
                return ResourceManager.GetString("MoreFromLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Fïñδ ₥ôřè βúïℓδƨ ƨôúřçèδ ƒřô₥ {0} ℓô !!!].
        /// </summary>
        public static string MoreFromSource {
            get {
                return ResourceManager.GetString("MoreFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Fïñδ ₥ôřè βúïℓδƨ çô₥ƥïℓèδ ïñ {0} ℓô !!!].
        /// </summary>
        public static string MoreFromYear {
            get {
                return ResourceManager.GetString("MoreFromYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Nô ℓáβ ƨƭřïñϱ  !!!].
        /// </summary>
        public static string NoLab {
            get {
                return ResourceManager.GetString("NoLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÞřïƲáƭè  !!!].
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Þúβℓïç  !!!].
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Qúïçƙ-ƥáƨƭè  !!!].
        /// </summary>
        public static string QuickPaste {
            get {
                return ResourceManager.GetString("QuickPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèƭúřñ ƭô βúïℓδ ℓïƨƭïñϱ ℓ !!!].
        /// </summary>
        public static string ReturnToListing {
            get {
                return ResourceManager.GetString("ReturnToListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèƭúřñ ƭô βúïℓδ ôƲèřƲïèω ℓ !!!].
        /// </summary>
        public static string ReturnToOverview {
            get {
                return ResourceManager.GetString("ReturnToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §λářè  !!!].
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tôδá¥  !!!].
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! βúïℓδƨ  !!!].
        /// </summary>
        public static string xBuilds {
            get {
                return ResourceManager.GetString("xBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Vïèω á ℓïƨƭ ôƒ áℓℓ Wïñδôωƨ βúïℓδƨ çô₥ƥïℓèδ ïñ {0}, áñδ ωáƭçλ λôω Wïñδôωƨ δèƲèℓôƥèδ ƨƭèáδïℓ¥ ôƲèř ƭï₥è, ƭλřôúϱλ ƭλè çôℓℓáβôřáƭïƲè βúïℓδ ℓïƨƭ, ßúïℓδFèèδ ℓôřè₥ ïƥƨú₥ δô !!!].
        /// </summary>
        public static string YearMetaGeneric {
            get {
                return ResourceManager.GetString("YearMetaGeneric", resourceCulture);
            }
        }
    }
}
