//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildFeed.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildFeed.Local.Model", typeof(Model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time created.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App package.
        /// </summary>
        public static string AppPackage {
            get {
                return ResourceManager.GetString("AppPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build time.
        /// </summary>
        public static string BuildTime {
            get {
                return ResourceManager.GetString("BuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build tools.
        /// </summary>
        public static string BuildTools {
            get {
                return ResourceManager.GetString("BuildTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string FlightHigh {
            get {
                return ResourceManager.GetString("FlightHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight level.
        /// </summary>
        public static string FlightLevel {
            get {
                return ResourceManager.GetString("FlightLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string FlightLow {
            get {
                return ResourceManager.GetString("FlightLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string FlightMedium {
            get {
                return ResourceManager.GetString("FlightMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FlightNone {
            get {
                return ResourceManager.GetString("FlightNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public leak.
        /// </summary>
        public static string InternalLeak {
            get {
                return ResourceManager.GetString("InternalLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab string.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak or release date.
        /// </summary>
        public static string LeakDate {
            get {
                return ResourceManager.GetString("LeakDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major version.
        /// </summary>
        public static string MajorVersion {
            get {
                return ResourceManager.GetString("MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor version.
        /// </summary>
        public static string MinorVersion {
            get {
                return ResourceManager.GetString("MinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time modified.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private leak.
        /// </summary>
        public static string PrivateLeak {
            get {
                return ResourceManager.GetString("PrivateLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public release.
        /// </summary>
        public static string PublicRelease {
            get {
                return ResourceManager.GetString("PublicRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source details.
        /// </summary>
        public static string SourceDetails {
            get {
                return ResourceManager.GetString("SourceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source type.
        /// </summary>
        public static string SourceType {
            get {
                return ResourceManager.GetString("SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (GDR).
        /// </summary>
        public static string UpdateGDR {
            get {
                return ResourceManager.GetString("UpdateGDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (LDR).
        /// </summary>
        public static string UpdateLDR {
            get {
                return ResourceManager.GetString("UpdateLDR", resourceCulture);
            }
        }
    }
}
