//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildFeed.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildFeed.Local.Model", typeof(Model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tï₥è çřèáƭèδ  !!!].
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âƥƥ ƥáçƙáϱè  !!!].
        /// </summary>
        public static string AppPackage {
            get {
                return ResourceManager.GetString("AppPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ ƭï₥è  !!!].
        /// </summary>
        public static string BuildTime {
            get {
                return ResourceManager.GetString("BuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ ƭôôℓƨ  !!!].
        /// </summary>
        public static string BuildTools {
            get {
                return ResourceManager.GetString("BuildTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ðôçú₥èñƭáƭïôñ  !!!].
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çáñář¥  !!!].
        /// </summary>
        public static string FlightCanary {
            get {
                return ResourceManager.GetString("FlightCanary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Fℓïϱλƭ ℓèƲèℓ  !!!].
        /// </summary>
        public static string FlightLevel {
            get {
                return ResourceManager.GetString("FlightLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Mïçřôƨôƒƭ Ìñƭèřñáℓ ℓ !!!].
        /// </summary>
        public static string FlightMSIT {
            get {
                return ResourceManager.GetString("FlightMSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Nôñè !!!].
        /// </summary>
        public static string FlightNone {
            get {
                return ResourceManager.GetString("FlightNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Óƥèřáƭïñϱ §¥ƨƭè₥ƨ Gřôúƥ ℓ !!!].
        /// </summary>
        public static string FlightOSG {
            get {
                return ResourceManager.GetString("FlightOSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Wïñδôωƨ Ìñƨïδèř Fáƨƭ ℓ !!!].
        /// </summary>
        public static string FlightWIF {
            get {
                return ResourceManager.GetString("FlightWIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Wïñδôωƨ Ìñƨïδèř §ℓôω ℓ !!!].
        /// </summary>
        public static string FlightWIS {
            get {
                return ResourceManager.GetString("FlightWIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Þúβℓïç ℓèáƙ  !!!].
        /// </summary>
        public static string InternalLeak {
            get {
                return ResourceManager.GetString("InternalLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £áβ ƨƭřïñϱ  !!!].
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £èáƙ ôř řèℓèáƨè δáƭè ℓ !!!].
        /// </summary>
        public static string LeakDate {
            get {
                return ResourceManager.GetString("LeakDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ôϱϱïñϱ  !!!].
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! MáJôř Ʋèřƨïôñ  !!!].
        /// </summary>
        public static string MajorVersion {
            get {
                return ResourceManager.GetString("MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Mïñôř Ʋèřƨïôñ  !!!].
        /// </summary>
        public static string MinorVersion {
            get {
                return ResourceManager.GetString("MinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tï₥è ₥ôδïƒïèδ  !!!].
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ ñú₥βèř  !!!].
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÞřïƲáƭè ℓèáƙ  !!!].
        /// </summary>
        public static string PrivateLeak {
            get {
                return ResourceManager.GetString("PrivateLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Þúβℓïç řèℓèáƨè  !!!].
        /// </summary>
        public static string PublicRelease {
            get {
                return ResourceManager.GetString("PublicRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδ řèƲïƨïôñ  !!!].
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ôúřçè δèƭáïℓƨ  !!!].
        /// </summary>
        public static string SourceDetails {
            get {
                return ResourceManager.GetString("SourceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! §ôúřçè ƭ¥ƥè  !!!].
        /// </summary>
        public static string SourceType {
            get {
                return ResourceManager.GetString("SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ûƥδáƭè (GÐR)  !!!].
        /// </summary>
        public static string UpdateGDR {
            get {
                return ResourceManager.GetString("UpdateGDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ûƥδáƭè (£ÐR)  !!!].
        /// </summary>
        public static string UpdateLDR {
            get {
                return ResourceManager.GetString("UpdateLDR", resourceCulture);
            }
        }
    }
}
