//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildFeed.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Support {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Support() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildFeed.Local.Support", typeof(Support).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ÉƲèř¥ áççôúñƭ ïƨ Ʋáℓïδáƭèδ β¥ áñ Âδ₥ïñïƨƭřáƭôř, ƨô βè ƥáƭïèñƭ áñδ çλèçƙ áϱáïñ ℓáƭèř. ℓôřè₥ ï !!!].
        /// </summary>
        public static string AccountValidation {
            get {
                return ResourceManager.GetString("AccountValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Âδδïƭïôñƨ ƭô ßúïℓδFèèδ ℓ !!!].
        /// </summary>
        public static string AdditionsToBuildFeed {
            get {
                return ResourceManager.GetString("AdditionsToBuildFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδƨ Çô₥ƥïℓèδ ℓ !!!].
        /// </summary>
        public static string BuildsCompiled {
            get {
                return ResourceManager.GetString("BuildsCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çλáñϱè ¥ôúř ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çôñƒïř₥ ñèω ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Çôñƒïř₥ ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! É₥áïℓ áδδřèƨƨ  !!!].
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éñƭèř çúřřèñƭ ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string EnterCurrentPassword {
            get {
                return ResourceManager.GetString("EnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éñƭèř ñèω ƥáƨƨωôřδ ℓ !!!].
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Éñƭèř ƥáƨƨωôřδ  !!!].
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Hïϱλèƨƭ Ʋèřƨïôñ ℓ !!!].
        /// </summary>
        public static string HighestVersion {
            get {
                return ResourceManager.GetString("HighestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £áβƨ !!!].
        /// </summary>
        public static string Labs {
            get {
                return ResourceManager.GetString("Labs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! £ôϱ ïñ  !!!].
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Þáƨƨωôřδ  !!!].
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèçèñƭℓ¥ áδδèδ  !!!].
        /// </summary>
        public static string RecentlyAdded {
            get {
                return ResourceManager.GetString("RecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèçèñƭℓ¥ çô₥ƥïℓèδ ℓ !!!].
        /// </summary>
        public static string RecentlyCompiled {
            get {
                return ResourceManager.GetString("RecentlyCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèçèñƭℓ¥ ℓèáƙèδ ℓ !!!].
        /// </summary>
        public static string RecentlyLeaked {
            get {
                return ResourceManager.GetString("RecentlyLeaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèϱïƨƭèř  !!!].
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rè₥è₥βèř ₥è  !!!].
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! ßúïℓδƨ çô₥ƥïℓèδ èáçλ 9úářƭèř ℓô !!!].
        /// </summary>
        public static string StatsCompiled {
            get {
                return ResourceManager.GetString("StatsCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Rèçôřδèδ βúïℓδƨ ïñ èáçλ ℓáβ ℓô !!!].
        /// </summary>
        public static string StatsLab {
            get {
                return ResourceManager.GetString("StatsLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Óñℓ¥ ℓáβƨ ωïƭλ 100 ôř ₥ôřè řèçôřδèδ βúïℓδƨ ářè ïñçℓúδèδ. ℓôřè₥ !!!].
        /// </summary>
        public static string StatsLabIncluded {
            get {
                return ResourceManager.GetString("StatsLabIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Nèω áδδïƭïôñƨ ƭô ßúïℓδFèèδ ôƲèř ƭλè ƥřèƲïôúƨ ¥èář ℓôřè !!!].
        /// </summary>
        public static string StatsNewAdditions {
            get {
                return ResourceManager.GetString("StatsNewAdditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Tλáñƙ ¥ôú ƒôř řèϱïƨƭèřïñϱ ℓô !!!].
        /// </summary>
        public static string ThanksRegister {
            get {
                return ResourceManager.GetString("ThanksRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Ûƨèřñá₥è  !!!].
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!!! Wèèƙ !!!].
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
